apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      imagePullSecrets: 
      - name: docker-hub
      containers:
      - name: my-app
        image: vladsanyuk/java-app:monitoring
        ports:
        - containerPort: 8080
        env:
        - name: DB_USER
          value: app-user
        - name: DB_PWD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-password
        - name: DB_SERVER
          valueFrom:
            configMapKeyRef:
              name: my-app-config
              key: db_url
        - name: DB_NAME
          value: app-db
---
apiVersion: v1
kind: Service
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  type: NodePort
  selector:
    app: my-app
  ports:
    - name: my-app-port
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: my-app-metrics-port
      protocol: TCP
      port: 8081
      targetPort: 8081
